### ISSUE TITLE
String vs array error

### ISSUE THREAD

**Issue by dvida** [mrprompt/fovthreed#2]
We've been getting this error lately:
`Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /var/www/html/globalmeteornetwork.org/fov3d/FOV3D.class.php:88 Stack trace: #0 /var/www/html/globalmeteornetwork.org/fov3d/FOV3D.class.php(88): implode() #1 /var/www/html/globalmeteornetwork.org/fov3d/process.php(78): GoogleEarthStation->addPlacemark() #2 {main} thrown in /var/www/html/globalmeteornetwork.org/fov3d/FOV3D.class.php on line 88`

Could you possibly take a look?
You can see the error live here: https://globalmeteornetwork.org/fov3d/

Thanks!

**Comment by mrprompt** [comment]
Fixed!
